repo: https://github.com/zer0yu/picker
proxy:
  url: 'http://127.0.0.1:7890'
  rss: false
  bot: false
rss:
  CustomRSS:
    enabled: false
    filename: CustomRSS.opml
  ResearchRSS:
    enabled: true
    filename: ResearchRSS.opml
  Subscriptions-OnMyMac:
    enabled: true
    filename: Subscriptions-OnMyMac.opml
  CyberSecurityRSS:
    enabled: false
    url: >-
      https://raw.githubusercontent.com/zer0yu/CyberSecurityRSS/master/CyberSecurityRSS.opml
    filename: CyberSecurityRSS.opml
  CyberSecurityRSS-tiny:
    enabled: true
    url: 'https://raw.githubusercontent.com/zer0yu/CyberSecurityRSS/master/tiny.opml'
    filename: CyberSecurityRSS-tiny.opml
  Chinese-Security-RSS:
    enabled: true
    url: >-
      https://raw.githubusercontent.com/zhengjim/Chinese-Security-RSS/master/Chinese-Security-RSS.opml
    filename: Chinese-Security-RSS.opml
  awesome-security-feed:
    enabled: false
    url: >-
      https://raw.githubusercontent.com/mrtouch93/awesome-security-feed/main/security_feeds.opml
    filename: awesome-security-feed.opml
  SecurityRSS:
    enabled: true
    url: 'https://github.com/Han0nly/SecurityRSS/blob/master/SecureRss.opml'
    filename: SecureRss.opml
  wechatRSS:
    enabled: true
    url: 'https://wechat2rss.xlab.app/opml/sec.opml'
    filename: wechatRSS.opml
  chinese-independent-blogs:
    enabled: true
    url: >-
      https://raw.githubusercontent.com/timqian/chinese-independent-blogs/master/feed.opml
    filename: chinese-independent-blogs.opml
bot:
  feishu:
    enabled: false
    secrets: FEISHU_KEY
    key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  wecom:
    enabled: false
    secrets: WECOM_KEY
    key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  dingtalk:
    enabled: true
    secrets: DINGTALK_KEY
    key: DINGTALK_KEY
    secret: DINGTALK_SECRET
  qq:
    enabled: false
    secrets: QQ_KEY
    qq_id: '2419110059'
    group_id:
      - '808542982'
      - '217863340'
    key: xxxxxxxxxx
  telegram:
    enabled: false
    secrets: TELEGRAM_KEY
    chat_id:
      - '-799557100'
    key: xxxxxxxxxx
  mail:
    enabled: true
    secrets: njtawpsixofkffba
    key: njtawpsixofkffba
    secrets_receiver: tyaookk@gmail.com
    receiver: tyaookk@gmail.com
    address: tyao27@qq.com
    server: smtp.qq.com
    from: security-bot <tyao27@qq.com>
pick_bot:
  dingtalk:
    enabled: false
    secrets: DINGTALK_KEY
    key: DINGTALK_KEY
    secret: DINGTALK_SECRET
